global using CentroEspecialidadesDentales.Domain.Common;
global using CentroEspecialidadesDentales.Domain.Entities;
global using CentroEspecialidadesDentales.Domain.Enums;
global using CentroEspecialidadesDentales.Domain.Events;
global using CentroEspecialidadesDentales.Domain.Exceptions;
global using CentroEspecialidadesDentales.Domain.ValueObjects;